name: CD

# Controls when the action will run.
on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release
    if: "!contains(github.event.head_commit.author.email, 'optdev@qhrtech.com')"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js v12.16.1
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.16.1

      - run: npm ci

      - run: |
          git status
          git config --global user.email "optdev@qhrtech.com"
          git config --global user.name "QHRLodestoneBot"

      - name: Release
        run: |
          npx nx run test-app:release
